steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=eu.gcr.io/$PROJECT_ID/git-lfs', '.']

# Simple unit test: invoke the new gcloud container to confirm that it was
# built correctly.
- name: 'eu.gcr.io/$PROJECT_ID/git-lfs'
  args:
  - "lfs"
  - "--help"

images: ['eu.gcr.io/$PROJECT_ID/git-lfs']
tags: ['cloud-builders-community']
